@startuml

' openplanner
package openplanner <<Node>> {
  note "17.4 k" as openplanner

  class PlannerH
  note bottom : 軌道生成機能を持つ
  class LocalPlannerH
  class BehaviorStateMachine {
    {abstract} BehaviorStateMachine* GetNextState()
  }
  class ForwardState
  class FollowState
  class BehaviorState
  note bottom: INITIAL_STATE, WAITING_STATE,\nFORWARD_STATE, STOPPING_STATE,\nEMERGENCY_STATE,TRAFFIC_LIGHT_STOP_STATE,\nTRAFFIC_LIGHT_WAIT_STATE, STOP_SIGN_STOP_STATE,\nSTOP_SIGN_WAIT_STATE, FOLLOW_STATE,\nLANE_CHANGE_STATE, OBSTACLE_AVOIDANCE_STATE,\nGOAL_STATE, FINISH_STATE
  class TrajectoryCosts
  note right : DetectedObject を入力として判断する
  class TrajectoryCost {
    int index;
    int relative_index;
    double closest_obj_velocity;
    double distance_from_center;
    double priority_cost; //0 to 1
    double transition_cost; // 0 to 1
    double closest_obj_cost; // 0 to 1
    double cost;
    double closest_obj_distance;

    int lane_index;
    double lane_change_cost;
    double lateral_cost;
    double longitudinal_cost;
    bool bBlocked;
    std::vector<std::pair<int, double> > lateral_costs;
  }
  class TrajectoryFollower
  class PlanningParam {
  PlanningParams() {
		maxSpeed = 3;
		minSpeed = 0;
		planningDistance = 10000;
		microPlanDistance = 30;
		carTipMargin = 4.0;
		rollInMargin = 12.0;
		rollInSpeedFactor = 0.25;
		pathDensity = 0.25;
		rollOutDensity = 0.5;
		rollOutNumber = 4;
		horizonDistance = 120;
		minFollowingDistance = 35;
		minDistanceToAvoid = 15;
		maxDistanceToAvoid = 5;
		speedProfileFactor = 1.0;
		smoothingDataWeight = 0.45;
		smoothingSmoothWeight = 0.3;
		smoothingToleranceError = 0.05;

		verticalSafetyDistance = 0.0;
		horizontalSafetyDistancel = 0.0;

		enableHeadingSmoothing = false;
		enableSwerving = false;
		enableFollowing = false;
		enableTrafficLightBehavior = false;
		enableLaneChange = false;
		enableStopSignBehavior = false;
		enabTrajectoryVelocities = false;

		enableDynamicPlannerS = false;
	}
}

LocalPlannerH o-- BehaviorStateMachine
LocalPlannerH *-- TrajectoryCosts
LocalPlannerH --> PlannerH
BehaviorStateMachine <|-- ForwardState
BehaviorStateMachine <|-- FollowState
TrajectoryCosts "1" *-- "*" TrajectoryCost

' dp_planner
package dp_planner <<Node>> {
  note "1.8 k" as dp_planner

class PlannerX
}

PlannerX *-- LocalPlannerH
PlannerX *-- BehaviorState

' ff_waypoint_follower
package ff_waypoint_follower <<Node>> {
  note "1.6 k" as ff_waypoint_follower

  class FFSteerControl
}

FFSteerControl *-- LocalPlannerH
FFSteerControl *-- TrajectoryFollower
FFSteerControl *-- BehaviorState

' way_planner
package way_planner <<Node>> {
  note "1.4 k" as way_planner

  class way_planner_core
}

way_planner_core *-- PlannerH

@enduml
